@startuml Login scenario
skinparam Style strictuml

!include <tupadr3/common>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/database>
!include <tupadr3/font-awesome/user>

FA_USER(Client, Client, participant, blue)
FA_SERVER(Server, Server, participant, Green)
FA_DATABASE(DB, Database, participant, Orange)

title Login scenario

Client -> Server : POST Login with user's credential
note left : here is a note\nfor you
activate Server
Client --> Client : Terminate on Network error

Client <-- Server : Terminate on Server Error
Server -> DB : POST to get User's info
activate DB
Server <- DB : Return exist user if match \nor nothing if no match found
deactivate DB
Server -> Server : Compare User credential \nfrom Client and DB

Client <- Server : Login succeed with session identifier\n(cookie/JWT)
deactivate Server

@enduml