@startmindmap
' skinparam Monochrome reverse
!theme crt-green

<style>
.dotBox * {
	LineStyle 5
    LineThickness 2
    LineColor green
}

.activate {
	BackgroundColor green
}
.deactivate {
	BackgroundColor Sienna
}
</style>

+ <&flag>Presentation ideas

++ plantUML 
+++ What is it? <<activate>>

' ++++ UML - Unified Modeling Language <<dotBox>>
' ****:plantUML and
' plantUML extension on VS code;


+++ Purpose / benefits

' ++++ Helps us to create a visual representation/documentation of our code flow
' ++++ Support many kinds of diagram: class, object, sequence, activity, and use case diagrams.
' ++++ Easy to update


***:code example: a login scenario
client, server, database;


' ***:customize style with
'  - skinparam [__skinProp__] [__propValue__]
'  - !theme [__themeName__];


+++ add diagram to github via PlantUML proxy service

' ****: add this line to your markdown file
' ![alternativeText](http://www.plantuml.com/plantuml/proxy?src=RESOURCE&idx=INDEX&fmt=FORMAT);



' REMOVED

' -- i18next <<dotBox>>
' --- WTH is this?
' --- Where to apply (i18next)
' ---- ReactJS 
' ---- Server side 


@endmindmap