@startmindmap

' skinparam HPmindmap {

' }
skinparam Monochrome reverse

+ <&flag>Presentation ideas

++[#lightgreen] plantUML
+++ WTH is this?
++++ UML - Unified Modeling Language
****: plantUML and
plantUML extension on VS code;
+++ code example
***:style with parameters
skinparam xxx;
***:add diagram to github via url
![alternativeText](http://www.plantuml.com/plantuml/proxy?cache=no&src=https:////raw.githubusercontent.com/{{userName}}/{{repoName}}/{{branch}}/{{filePath}});


--[#Lightgrey] i18next
--- WTF is this?
--- Where to apply (i18next)
---- ReactJS
---- Server side


@endmindmap